### ISSUE TITLE
Crash on trying to break a block while in settings menu

### ISSUE THREAD

**Issue by Craluminum2413** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#1]
**Describe the Bug:**
Game crashes on trying to break the block in creative mod while settings menu (`.wpSettings`) is opened.

**To Reproduce:**
1. Load single player world
2. Get creative gamemode
3. Make sure you aiming at some block
4. Run `.wpSettings` command
5. While window is opened, hover a mouse out of window area
6. Press `Alt` and `Left-click` at the same time, thus, breaking the block
7. Game crashes

**Expected Behaviour:**
It locks controls

**Additional Context**
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0 (Stable)01/12/2022 22:10:27: Critical error occurred
System.Exception: Call to RegisterCallback while game is paused
   at Vintagestory.Client.NoObf.ClientMain.RegisterCallback(Action`1 OnTimePassed, Int32 millisecondDelay)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _lb8GGBWOchQLOU3RFFw58Ijkh1D._uA6fxRiik2om8WbTxul2Dtkekip(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
```

**Comment by ApacheTech** [comment]
This is only an issue in Developer Mode, and with Extended Debug Info enabled. 

```
    if (ClientSettings.DeveloperMode && this.extendedDebugInfo)
    {
        throw new Exception("Call to RegisterCallback while game is paused");
    }
```

However, this is now fixed, with the addition of a `DisableMouseGrab` flag within the GUI Dialogue window.

Thank you.
