### ISSUE TITLE
[BUG] PlayerPins has a race condition with spawning algorithm, when going through TLs.

### ISSUE THREAD

**Issue by ApacheTech** [ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer#2]
**Describe the Bug:**
```
Running on 64 bit Windows with 16 GB RAM 
Version: v1.16.0 (Stable)2022-01-15 00:51:06: Critical error occurred
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary2.get_Item(TKey key)
   at ApacheTech.VintageMods.CampaignCartographer.Features.PlayerPins.PlayerPinsMapLayer.OnPlayerSpawn(IPlayer player)
   at Vintagestory.Client.NoObf.ClientSystemEntities.OnEntityDespawn(Entity entity, EntityDespawnReason despawnReason)
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerEntityDespawn(Entity entity, EntityDespawnReason despawnReason)
   at Vintagestory.Client.NoObf.SystemUnloadChunks.UnloadChunk(ClientChunk clientchunk)
   at Vintagestory.Client.NoObf.SystemUnloadChunks.HandleChunkUnload(_hpqb4cNQuSfxZLdFacKLPiYYWAN packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _lb8GGBWOchQLOU3RFFw58Ijkh1D._uA6fxRiik2om8WbTxul2Dtkekip(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._HuDdfzha8ZKZvU2y0RbH58r7VzR(Single )
   at _vFhcDU5n6Z0hUte90jdaxlrDjR5._XZOFA2JA54yZjH15yys9W7vL9hj(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 479
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 454
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at _FKpOpQGqqf3cJWdQyWh1ysxsDBb._pYad7oBcQ5qtzQkYGDu4NFHQxhK(_5x3PJgrln4IBXPDNSNN0fecxKFb , String[] )
   at _sejP0Tcz8wTg70ptIdRr3CwQmrE._pYad7oBcQ5qtzQkYGDu4NFHQxhK(ThreadStart )
```

**To Reproduce:**
Steps to reproduce the behaviour:
1. Launch the game with mod installed.
2. Repair a translocator.
3. Head straight through.

**Expected Behaviour:**
You should spawn on the other side, and the map should update naturally.

**Additional Context**
`PlayerPinsMapLayer::OnPlayerSpawn(IPlayer player)` seems to be the culprit.

https://github.com/ApacheTechSolutions/ApacheTech.VintageMods.CampaignCartographer/blob/master/ApacheTech.VintageMods.CampaignCartographer/Features/PlayerPins/PlayerPinsMapLayer.cs#L62

**Comment by ApacheTech** [comment]
Fixed in 2.0.0-pre.2.
